### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by owen927** [sitzikbs/3DmFV-Net#2]
Hello Itzik,

I noticed that a few files are missing in the repo, I was able to find them from pointnet repo but you might want to include them.

List of files missing:
model\transform_net.py
tf_ops\tf_auctionmatch.py
tf_ops\tf_sampling.py

**Comment by sitzikbs** [comment]
Hi @owen927 , 
Thanks for your comment. 
These files are not required to run 3dmfv. If they appear anywhere, it is an oversight on my part when I was cleaning up the code. 

I see that transform_net appears in voxnet_3dmfv.py. It can be removed since it is not required and unused (line 11). 
Where did you see the others in my code? 

I can fix it in a while or you can issue a pull request.

**Comment by owen927** [comment]
Hi Itzik,

Thank you for the speedy response.

The functions from tf_auctionmatch.py and tf_sampling.py are used in the get_loss function in fv_decoder, which isn't being used at the moment.

I can put up a pull request removing the get_loss function and references to these files if they are not needed.

Also wanted to let you know that the code is working for Windows 10 with python 3.6, tensorflow 1.12, cuda 9.0.176 and cudnn 9.0

Thanks again for sharing your work!

**Comment by sitzikbs** [comment]
Yes, I remember now. I used their EMD loss to train the decoder. There is also a chamfer loss that doesn't need them. 
Let me clean it up myself in a few days (after CVPR submission).  I wouldn't remove the get_loss function since it will not be possible to train without it. 
I'll leave the issue open until I take care of this. 

Thanks for the info regarding your testing environment, I will add it to the readme file.

**Comment by owen927** [comment]
Ah I see, no hurry on the changes. Good luck with the CVPR submission!
P.S. if you are going to update the readme file, adding a download link to the test data set might also be a good idea (https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip).

**Comment by sitzikbs** [comment]
Thanks for your comments. I have resolved all of the issues you mentioned (I hope). 
Let me know if there are still any problems.
